<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE employeehandler [
             <!ENTITY version "V0.01 (C) CashewOutside 2019">
             <!ELEMENT employeehandler (employees)>
             <!ELEMENT employees (employee*)>
             <!ELEMENT employee (username, password, salt)>
             <!ELEMENT username (#PCDATA)>
             <!ELEMENT password (#PCDATA)>
             <!ELEMENT salt (#PCDATA)>
             <!ATTLIST employee
                     hasAdminRights (true|false) #REQUIRED
                     >
             ]>
<employeehandler>
   <employees>
      <employee hasAdminRights="true">
         <username>manager</username>
         <password>o0okYAs2nOZ9nwymbnEC39xhxv08NPtWjUnVHpMoKVM6z5k0YUCyzytuSqVdIgf24wYl9q+TW4TarqwESNyZgQ==</password>
         <salt>
                GFncbLfVUoA6ry05lcFkXgCXf6/0YCfVVuJQ/AQ5wf16PN5M9McRrWkQ6RPhUpvtr6dNiJvt4UHze7uHtwUuHeIUBg5Db5bRtoiL9XjDkRahS0KUTkn3Ej0YL1fHRWXxfHY83HGXUelehzc1eoJCsCqI0j92pa5phdqAJ1lkRoQkgMNI5s00HJTcaeUvztylBA9W6yCB1VTCDxcgBcv5cFLM6Cl/wGsBjoEs/ar5uh0demiry/r2tlclOUvuFkjMWuxceKnWKJFhIIAOjCAnwJw9kmJ96HRW/2tLwVM3uk9uOSEOuglEFMDZnDVHCNyAxA4QYxiYNQXGCMYLMifT/RTo3gE6nYR12VD43D7CLijSDuGjaTo0LoVH22pouv0rrMHrO47EeyLXiMT3C8tKJ3I4dEKirl5v0gldmRVERYIEwDP1mYFjpuFsO7jeea8w0MdTnHrNfZop3KvU31GzLe2ffrePGJ4cVIsMiFfDrVy42xwevKDZeiovpl/PR0wSV1DEBJiVw10gUARHqlcXdz0E76JM09S8Gp/r7chN4rF02mMGrxiEVNDZWUCDKJtVyMDZ6z2b+iujvVkkgW7mQdMGfy5QtlWMvm56QuHEEj/COsIS/+75Mka3qH1MIGuwZq+RxUu1045kSctBkUvWaQje1Jl5vJn9Ydu5LsQJgOw=
            </salt>
      </employee>
   </employees>
</employeehandler>
