<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE sales [
        <!ENTITY version "V0.01 (C) CashewOutside">
        <!ELEMENT sales (orders)>
        <!ELEMENT orders (order*)>
        <!ELEMENT order (orderId, customerName, orderStatus, orderCost, itemsOrdered*, flagsChecked)>
        <!ATTLIST order
                dateOrdered CDATA #REQUIRED
                timeOrdered CDATA #REQUIRED
                isGF (YES|NO|UNKNOWN) "NO"
                isVegan (YES|NO|UNKNOWN) "NO"
                isVeg (YES|NO|UNKNOWN) "UNKNOWN"
                >
        <!ELEMENT orderId (#PCDATA)>
        <!ELEMENT customerName (#PCDATA)>
        <!ELEMENT orderStatus (#PCDATA)>
        <!ELEMENT orderCost (#PCDATA)>
        <!ELEMENT itemsOrdered (id, name)>
        <!ELEMENT flagsChecked (#PCDATA)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        ]>
<sales>
   <orders>
       <order dateOrdered="2019-10-05" timeOrdered="02:07:37.649546600">
         <orderId>3</orderId>
         <customerName>Ooo a</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>3382.0</orderCost>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>BB1</id>
            <name>Beefburger</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>Lem</id>
            <name>LemCan</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
       <order dateOrdered="2019-10-05" timeOrdered="02:07:37.650543800">
         <orderId>4</orderId>
         <customerName>This is IT</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>6244.0</orderCost>
         <itemsOrdered>
            <id>BB1</id>
            <name>Beefburger</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
       <order dateOrdered="2019-10-05" timeOrdered="02:07:37.651545800">
         <orderId>5</orderId>
         <customerName>JErome</customerName>
         <orderStatus>COMPLETE</orderStatus>
         <orderCost>6245.0</orderCost>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>BB1</id>
            <name>Beefburger</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>Lem</id>
            <name>LemCan</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
       <order dateOrdered="2019-10-05" timeOrdered="02:07:37.652538600">
         <orderId>7</orderId>
         <customerName>Hunter</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>721.0</orderCost>
         <itemsOrdered>
            <id>BB1</id>
            <name>Beefburger</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>HotChoc</id>
            <name>Hot Chocolate</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>Lem</id>
            <name>LemCan</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
       <order dateOrdered="2019-10-05" timeOrdered="02:07:37.653535700">
         <orderId>9</orderId>
         <customerName>hooha</customerName>
         <orderStatus>COMPLETE</orderStatus>
         <orderCost>220.0</orderCost>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
       <order dateOrdered="2019-10-05" timeOrdered="02:07:37.653535700">
         <orderId>10</orderId>
         <customerName>hahoo</customerName>
         <orderStatus>COMPLETE</orderStatus>
         <orderCost>220.0</orderCost>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
       <order dateOrdered="2019-10-05" timeOrdered="02:07:37.653535700">
         <orderId>11</orderId>
         <customerName>hoo</customerName>
         <orderStatus>COMPLETE</orderStatus>
         <orderCost>220.0</orderCost>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
       <order dateOrdered="2019-10-05" timeOrdered="02:07:37.654533200">
         <orderId>12</orderId>
         <customerName>long dong duk</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>220.0</orderCost>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
       <order dateOrdered="2019-10-05" timeOrdered="02:07:37.654533200">
         <orderId>13</orderId>
         <customerName>dong</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>220.0</orderCost>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
   </orders>
</sales>
