<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE suppliers [
        <!ENTITY version "V0.01 (C) CashewOutside 2019">
        <!ELEMENT suppliers (description, providers)>
        <!ELEMENT providers ((supplier*))>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT supplier (sid, name, address, phone, email?, url?)>
        <!ELEMENT sid (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT phone (#PCDATA)>
        <!ATTLIST supplier type (MOBILE|WORK|HOME|UNKNOWN) "UNKNOWN">
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT url (#PCDATA)>
        ]>
<suppliers>
    <description>Some sample supplier data</description>
    <providers>
        <supplier type="MOBILE">
            <sid>s3</sid>
            <name>Admiral Benjamin's Seafoods</name>
            <address>86 Low Street, Christchurch</address>
            <phone>021345666</phone>
            <email>bigben@cfoods.co.nz</email>
            <url>cfoods.co.nz</url>
        </supplier>
        <supplier type="WORK">
            <sid>s4</sid>
            <name>Dave's Drinks</name>
            <address>Unit 5, Bert's Business Park, Christchurch</address>
            <phone>3515666</phone>
            <email>daved@davesdrinks.co.nz</email>
            <url></url>
        </supplier>
    </providers>
</suppliers>
