<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE sales [
        <!ENTITY version "V0.01 (C) CashewOutside">
        <!ELEMENT sales (orders)>
        <!ELEMENT orders (order*)>
        <!ELEMENT order (orderId, customerName, orderStatus, orderCost, itemsOrdered*, flagsChecked)>
        <!ATTLIST order
                dateOrdered CDATA #REQUIRED
                timeOrdered CDATA #REQUIRED
                isGF (YES|NO|UNKNOWN) "NO"
                isVegan (YES|NO|UNKNOWN) "NO"
                isVeg (YES|NO|UNKNOWN) "UNKNOWN"
                >
        <!ELEMENT orderId (#PCDATA)>
        <!ELEMENT customerName (#PCDATA)>
        <!ELEMENT orderStatus (#PCDATA)>
        <!ELEMENT orderCost (#PCDATA)>
        <!ELEMENT itemsOrdered (id, name)>
        <!ELEMENT flagsChecked (#PCDATA)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        ]>
<sales>
   <orders>
      <order dateOrdered="2019-09-29" timeOrdered="21:46:39.450253">
         <orderId>1</orderId>
         <customerName>Woot Woot</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>1.0</orderCost>
         <itemsOrdered>
            <id>Lem</id>
            <name>LemCan</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
      <order dateOrdered="2019-09-29" timeOrdered="21:46:39.452509">
         <orderId>2</orderId>
         <customerName>Hunter</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>3505.0</orderCost>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>HotChoc</id>
            <name>Hot Chocolate</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
      <order dateOrdered="2019-09-29" timeOrdered="21:46:39.453063">
         <orderId>3</orderId>
         <customerName>Ooo a</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>3382.0</orderCost>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>BB1</id>
            <name>Beefburger</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>Lem</id>
            <name>LemCan</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
      <order dateOrdered="2019-09-29" timeOrdered="21:46:39.453964">
         <orderId>4</orderId>
         <customerName>This is IT</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>6244.0</orderCost>
         <itemsOrdered>
            <id>BB1</id>
            <name>Beefburger</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
      <order dateOrdered="2019-09-29" timeOrdered="21:46:39.454491">
         <orderId>5</orderId>
         <customerName>JErome</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>6245.0</orderCost>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CAV</id>
            <name>Coq au van</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>BB1</id>
            <name>Beefburger</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>Lem</id>
            <name>LemCan</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
      <order dateOrdered="2019-09-29" timeOrdered="21:46:39.455091">
         <orderId>7</orderId>
         <customerName>Hunter</customerName>
         <orderStatus>QUEUED</orderStatus>
         <orderCost>721.0</orderCost>
         <itemsOrdered>
            <id>BB1</id>
            <name>Beefburger</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>CF</id>
            <name>Chicken fried rice</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>HotChoc</id>
            <name>Hot Chocolate</name>
         </itemsOrdered>
         <itemsOrdered>
            <id>Lem</id>
            <name>LemCan</name>
         </itemsOrdered>
         <flagsChecked>true</flagsChecked>
      </order>
   </orders>
</sales>
